import {prepareLegacyReadModel} from '../src/legacyReadModelRehearsal.js';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {initializeApp,deleteApp} from 'firebase-admin/app';
import {getFirestore} from 'firebase-admin/firestore';
import {applyAdminDomain} from '../src/adminDomain.js';
import {refreshLegacyLobby} from '../src/legacyLobbyProjection.js';
import {syncMemberSummary,queueClubHomeRefresh,processHomeSummaryPage,refreshUserHomes} from '../src/homeProjection.js';
process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8082';
test('admin authority, protected cell, singleton notices and summary lifecycle',async()=>{
 const app=initializeApp({projectId:'demo-moyoung-ui'},'domain-'+Date.now());
 const db=getFirestore(app,'maintenance-'+Date.now());
 try{
  await db.doc('users/admin').set({role:'head_admin',name:'관리자'});
  await db.doc('users/member').set({role:'member',name:'회원'});
  await db.doc('cells/base').set({name:'둔산제일교회'});
  await assert.rejects(applyAdminDomain(db,'member',{action:'deleteCell',cellId:'base'}));
  await assert.rejects(applyAdminDomain(db,'admin',{action:'deleteCell',cellId:'base'}));
  await assert.rejects(applyAdminDomain(db,'admin',{action:'setRole',uid:'member',role:'server_admin'}));
  await assert.rejects(applyAdminDomain(db,'admin',{action:'reorganizeCells',names:[]}));
  await assert.rejects(applyAdminDomain(db,'admin',{action:'reorganizeCells',names:['중복','중복']}));
  await applyAdminDomain(db,'admin',{action:'reorganizeCells',names:['새 셀']});
  assert.equal((await db.doc('cells/base').get()).data().name,'둔산제일교회');
  assert.equal((await db.collection('cells').get()).size,2);
  await Promise.all(['첫 공지','다음 공지'].map(title=>applyAdminDomain(db,'admin',{action:'publishNotice',title,content:'본문'})));
  assert.equal((await db.collection('notices').get()).size,1);
  const club=db.doc('clubs/1');
  await club.set({name:'이전 이름',membershipSchemaVersion:1,leaderUids:[]});
  await db.doc('clubs/1/members/member').set({status:'active',role:'member'});
  await db.doc('users/member/_clubLinks/1').set({clubId:'1'});
  await syncMemberSummary(db,'1','member');
  await club.update({name:'변경 이름'});await queueClubHomeRefresh(db,'1');await processHomeSummaryPage(db,'1');
  const home=db.doc('users/member/summaries/home');
  assert.equal((await home.get()).data().clubs[0].name,'변경 이름');
  await db.doc('users/member').update({role:'guest'});await refreshUserHomes(db,'member');
  assert.equal((await home.get()).data().clubs.length,0);
  await db.doc('users/member').update({role:'member'});await refreshUserHomes(db,'member');
  assert.equal((await home.get()).data().clubs.length,1);
  await db.doc('lobby_settings/main').set({readModelVersion:1});
  await db.doc('club_schedules/a').set({id:1,club_id:1,title:'가까운 일정',startsAtMs:200,event_date:'2099-01-01'});
  await db.doc('club_schedules/b').set({id:2,club_id:1,title:'나중 일정',startsAtMs:300,event_date:'2099-01-02'});
  await refreshLegacyLobby(db,100);
  assert.equal((await db.doc('_readModels/lobby').get()).data().schedules[0].id,1);
  await refreshLegacyLobby(db,250);
  assert.equal((await db.doc('_readModels/lobby').get()).data().schedules[0].id,2);
  await db.doc('club_schedules/a').update({created_at:'2026-09-27T01:00:00Z'});
  await db.doc('club_schedules/b').update({created_at:'2026-09-27T01:00:00Z'});
  const migrated=await prepareLegacyReadModel(db,'1');
  assert.deepEqual(migrated,{sources:2,feed:2});
  assert.deepEqual(await prepareLegacyReadModel(db,'1'),migrated);
  await club.delete();await queueClubHomeRefresh(db,'1');await processHomeSummaryPage(db,'1');
  assert.equal((await home.get()).data().clubs.length,0);
 }finally{await db.terminate();await deleteApp(app);}
});
